apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kibana-proxy
  labels:
    app:  kibana-proxy
spec:
  selector:
    matchLabels:
      app: kibana-proxy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  kibana-proxy
    spec:
      containers:
      - name:  kibana-proxy
        image:  registry.cn-hongkong.aliyuncs.com/spotmax/maxcloud-proxy:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: TARGET_URL
            value: kibana-kibana:5601
          - name: AUTH_NAMW
            value: 'elastic'
          - name: AUTH_PASSWORD
            value: 'elastic'
        ports:
        - containerPort:  8080
          name:  kibana-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-proxy-svc
spec:
  selector:
    app: kibana-proxy
  type: LoadBalancer
  ports:
  - name: kibana-proxy-svc
    protocol: TCP
    port: 8080
    targetPort: 8080