apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: spotmax-maxcloud
stringData:
  all.yml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://kube-prometheus-stack-prometheus.spotmax-maxcloud.svc:9090",
                "version": 1
            }
        ]
    }
type: Opaque
