apiVersion: apps/v1
kind: Deployment
metadata:
  name:  grafana-proxy
  namespace: spotmax-maxcloud
  labels:
    app:  grafana-proxy
spec:
  selector:
    matchLabels:
      app: grafana-proxy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  grafana-proxy
    spec:
      containers:
      - name:  grafana-proxy
        image:  registry.cn-hongkong.aliyuncs.com/spotmax/maxcloud-proxy:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: TARGET_URL
            value: grafana-svc:3000
        ports:
        - containerPort:  8080
          name:  grafana-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy-svc
spec:
  selector:
    app: grafana-proxy
  type: LoadBalancer
  ports:
  - name: grafana-proxy-svc
    protocol: TCP
    port: 8080
    targetPort: 8080